/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from 'motia'

declare module 'motia' {
  interface Streams {}

  interface Enqueues {
    'platform.scrape': unknown
    'jobs.normalize': unknown
  }
}
