import type { AutopilotEvidence } from "@/src/autopilot/types/evidence";
import type { AutopilotFinding, FindingSeverity } from "@/src/autopilot/types/finding";

export interface FormattedIssue {
  title: string;
  body: string;
  labels: string[];
}

const CATEGORY_LABELS: Record<AutopilotFinding["category"], string> = {
  bug: "bug",
  ux: "ux",
  perf: "perf",
  "ai-quality": "ai-quality",
};

const SEVERITY_LABELS: Record<FindingSeverity, string> = {
  critical: "priority:critical",
  high: "priority:high",
  medium: "priority:medium",
  low: "priority:low",
};

function formatEvidenceLink(evidence: AutopilotEvidence): string {
  const link = evidence.url ?? `\`${evidence.path}\``;
  const label = evidence.url ? `[${evidence.kind}](${evidence.url})` : `${evidence.kind}: ${link}`;
  return `- ${label}`;
}

export function formatFindingAsIssue(
  finding: AutopilotFinding,
  evidence: AutopilotEvidence[],
  reportUrl?: string,
): FormattedIssue {
  const lines: string[] = [];

  // Hidden fingerprint marker for deduplication
  lines.push(`<!-- autopilot-fingerprint:${finding.fingerprint} -->`);
  lines.push("");

  // Metadata table
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Surface | \`${finding.surface}\` |`);
  lines.push(`| Category | \`${finding.category}\` |`);
  lines.push(`| Severity | \`${finding.severity}\` |`);
  lines.push(`| Confidence | ${(finding.confidence * 100).toFixed(0)}% |`);
  lines.push("");

  // Description
  lines.push("## Description");
  lines.push("");
  lines.push(finding.description);
  lines.push("");

  // Suspected root cause
  if (finding.suspectedRootCause) {
    lines.push("## Suspected Root Cause");
    lines.push("");
    lines.push(finding.suspectedRootCause);
    lines.push("");
  }

  // Recommended action
  if (finding.recommendedAction) {
    lines.push("## Recommended Action");
    lines.push("");
    lines.push(finding.recommendedAction);
    lines.push("");
  }

  // Evidence
  if (evidence.length > 0) {
    lines.push("## Evidence");
    lines.push("");
    for (const e of evidence) {
      lines.push(formatEvidenceLink(e));
    }
    lines.push("");
  }

  // Report link
  if (reportUrl) {
    lines.push(`📄 [Full autopilot report](${reportUrl})`);
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("🤖 Auto-generated by Motian Autopilot");

  return {
    title: `[autopilot] ${finding.title}`,
    body: lines.join("\n"),
    labels: ["autopilot", CATEGORY_LABELS[finding.category], SEVERITY_LABELS[finding.severity]],
  };
}
