/**
 * Import all Striive jobs from exported API JSON.
 * Usage: npx tsx scripts/import-striive-api.ts
 *
 * The JSON file is generated by copying the browser's API response
 * from https://supplier.striive.com/api/v2/job-requests?page=0&size=1000
 */
import { config } from "dotenv";

config({ path: ".env.local" });

import { readFileSync } from "node:fs";
import { sql } from "drizzle-orm";
import { db } from "../src/db";
import { jobs } from "../src/db/schema";

interface StriiveJob {
  id: number;
  title: string;
  client?: { id: number; name: string };
  locationName?: string;
  hoursPerWeek?: number;
  minHoursPerWeek?: number;
  startDate?: string;
  endDate?: string;
  publishedAt?: string;
  remoteAllowed?: string;
  referenceCode?: string;
  closingDateOffer?: string;
  typeOfProfessional?: string;
  state?: string;
}

function mapWorkArrangement(remote?: string): string | undefined {
  if (!remote) return undefined;
  switch (remote) {
    case "HYBRID":
      return "hybride";
    case "NO":
      return "op_locatie";
    case "YES":
      return "remote";
    default:
      return undefined;
  }
}

function extractProvince(location?: string): string | undefined {
  if (!location?.includes(" - ")) return undefined;
  return location.split(" - ")[1]?.trim();
}

async function main() {
  const raw = readFileSync("scripts/striive-jobs.json", "utf-8");
  const apiJobs: StriiveJob[] = JSON.parse(raw);

  console.log(`Loaded ${apiJobs.length} jobs from Striive API export`);

  let inserted = 0;
  let updated = 0;

  // Process in batches of 20
  for (let i = 0; i < apiJobs.length; i += 20) {
    const batch = apiJobs.slice(i, i + 20);

    const values = batch.map((j) => ({
      platform: "striive" as const,
      externalId: String(j.id),
      externalUrl: `https://supplier.striive.com/inbox/all/${j.id}`,
      clientReferenceCode: j.referenceCode,
      title: j.title,
      company: j.client?.name,
      location: j.locationName,
      province: extractProvince(j.locationName),
      startDate: j.startDate ? new Date(j.startDate) : undefined,
      endDate: j.endDate ? new Date(j.endDate) : undefined,
      applicationDeadline: j.closingDateOffer ? new Date(j.closingDateOffer) : undefined,
      postedAt: j.publishedAt ? new Date(j.publishedAt) : undefined,
      contractType: "freelance" as const,
      workArrangement: mapWorkArrangement(j.remoteAllowed),
      scrapedAt: new Date(),
      rawPayload: j as unknown as Record<string, unknown>,
    }));

    const result = await db
      .insert(jobs)
      .values(values)
      .onConflictDoUpdate({
        target: [jobs.platform, jobs.externalId],
        set: {
          title: sql`excluded.title`,
          company: sql`excluded.company`,
          location: sql`excluded.location`,
          province: sql`excluded.province`,
          externalUrl: sql`excluded.external_url`,
          clientReferenceCode: sql`excluded.client_reference_code`,
          startDate: sql`excluded.start_date`,
          endDate: sql`excluded.end_date`,
          applicationDeadline: sql`excluded.application_deadline`,
          workArrangement: sql`excluded.work_arrangement`,
          rawPayload: sql`excluded.raw_payload`,
          scrapedAt: sql`excluded.scraped_at`,
        },
      })
      .returning({ id: jobs.id, xmax: sql<string>`xmax` });

    const newCount = result.filter((r) => r.xmax === "0").length;
    inserted += newCount;
    updated += result.length - newCount;

    console.log(
      `Batch ${Math.floor(i / 20) + 1}: ${result.length} upserted (${newCount} new, ${result.length - newCount} updated)`,
    );
  }

  console.log(`\nDone: ${inserted} new, ${updated} updated, ${apiJobs.length} total`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Import failed:", err);
  process.exit(1);
});
